version: '3.5'

services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: colibris_fuseki
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  redis:
    image: redis
    container_name: colibris_redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]

  arena:
    build: ./arena
    container_name: arena
    restart: always
    volumes:
      - ./arena/config:/opt/arena/src/server/config
    depends_on:
      - redis
    ports:
      - "4567:4567"
    expose:
      - "4567"
    environment:
      REDIS_HOST: 'redis'
