version: '3.5'

services:
  fuseki:
    image: stain/jena-fuseki
    container_name: colibris_fuseki
    restart: always
    volumes:
      - ./data/rdf_data:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    environment:
      ADMIN_PASSWORD: "admin"

  redis:
    image: redis
    container_name: colibris_redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./data/redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
